In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('500_Person_Gender_Height_Weight_Index.csv')

In [3]:
df.head(3) # إظهار أول ثلاثة سطور 

Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Gender  500 non-null    object
 1   Height  500 non-null    int64 
 2   Weight  500 non-null    int64 
 3   Index   500 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 15.8+ KB


In [5]:
# إستخلاص القيم العددية من البيانات على شكل متجه 
arr = df.iloc[:,-3:].values
arr

array([[174,  96,   4],
       [189,  87,   2],
       [185, 110,   4],
       ...,
       [141, 136,   5],
       [150,  95,   5],
       [173, 131,   5]], dtype=int64)

In [6]:
# عدد أبعد المتجه
arr.ndim

2

In [7]:
# عدد عناصر المتجه
arr.size

1500

In [8]:
# شكل البيانات 
arr.shape

(500, 3)

In [9]:
# النوع المخزن فيه المتجه
arr.dtype

dtype('int64')

In [10]:
# العامود الأخير بشكل متجه
target = arr[:,-1]
target

array([4, 2, 4, 3, 3, 3, 5, 5, 3, 4, 2, 4, 3, 2, 2, 5, 5, 5, 5, 5, 5, 5,
       4, 5, 2, 3, 3, 1, 5, 5, 5, 1, 1, 5, 5, 4, 3, 4, 5, 2, 4, 5, 2, 5,
       4, 2, 4, 4, 3, 5, 5, 1, 5, 4, 4, 3, 4, 5, 3, 5, 0, 5, 0, 2, 5, 5,
       4, 2, 4, 4, 2, 4, 5, 2, 3, 4, 4, 4, 4, 0, 3, 5, 3, 4, 5, 0, 5, 5,
       5, 5, 5, 3, 3, 2, 4, 5, 4, 5, 1, 0, 4, 5, 5, 4, 4, 4, 5, 5, 4, 3,
       4, 5, 4, 2, 4, 3, 2, 5, 5, 5, 4, 4, 4, 5, 5, 4, 4, 4, 5, 2, 5, 2,
       5, 4, 5, 5, 5, 3, 5, 5, 2, 4, 5, 5, 5, 4, 3, 5, 3, 3, 0, 3, 3, 5,
       5, 4, 3, 5, 3, 4, 2, 2, 3, 5, 4, 2, 4, 5, 3, 2, 4, 5, 5, 4, 4, 4,
       4, 3, 5, 3, 3, 4, 4, 2, 3, 3, 5, 3, 5, 4, 5, 5, 4, 5, 5, 5, 4, 4,
       5, 5, 1, 3, 4, 4, 5, 4, 5, 4, 3, 4, 4, 5, 5, 5, 0, 5, 5, 5, 5, 5,
       2, 5, 4, 5, 0, 5, 3, 4, 5, 5, 4, 2, 3, 3, 4, 3, 5, 5, 2, 5, 3, 2,
       1, 5, 0, 5, 3, 5, 3, 4, 3, 5, 5, 5, 5, 2, 4, 5, 5, 4, 5, 5, 5, 2,
       4, 5, 5, 5, 5, 1, 5, 5, 4, 0, 3, 3, 4, 2, 3, 1, 1, 5, 5, 4, 4, 4,
       4, 5, 2, 5, 4, 3, 3, 4, 5, 5, 2, 4, 3, 4, 5,

In [11]:
# مرور على عناصر المتجه بثلاثة خطوات 
arr[::3,:]

array([[174,  96,   4],
       [195, 104,   3],
       [147,  92,   5],
       [169, 103,   4],
       [192, 101,   3],
       [153, 107,   5],
       [144, 145,   5],
       [153, 149,   5],
       [172,  67,   2],
       [187,  62,   1],
       [153, 121,   5],
       [160, 131,   5],
       [197, 114,   3],
       [185,  81,   2],
       [157,  56,   2],
       [185,  76,   2],
       [161,  72,   3],
       [176,  54,   1],
       [196, 116,   4],
       [178, 127,   5],
       [191,  54,   0],
       [190,  83,   2],
       [172,  96,   4],
       [194, 136,   4],
       [141,  80,   5],
       [197, 154,   4],
       [176, 122,   4],
       [166, 140,   5],
       [168, 123,   5],
       [145, 117,   5],
       [178, 154,   5],
       [177,  61,   2],
       [142,  69,   4],
       [190,  50,   0],
       [161, 155,   5],
       [195, 126,   4],
       [181, 106,   4],
       [146, 157,   5],
       [177,  96,   4],
       [146, 104,   5],
       [168,  87,   4],
       [184, 160

In [12]:
# أخذ أعمدة محددة
col1 = arr[:,0]
col3 = arr[:,-1]
col1.reshape(-1,1)

array([[174],
       [189],
       [185],
       [195],
       [149],
       [189],
       [147],
       [154],
       [174],
       [169],
       [195],
       [159],
       [192],
       [155],
       [191],
       [153],
       [157],
       [140],
       [144],
       [172],
       [157],
       [153],
       [169],
       [185],
       [172],
       [151],
       [190],
       [187],
       [163],
       [179],
       [153],
       [178],
       [195],
       [160],
       [157],
       [189],
       [197],
       [144],
       [171],
       [185],
       [175],
       [149],
       [157],
       [161],
       [182],
       [185],
       [188],
       [181],
       [161],
       [140],
       [168],
       [176],
       [163],
       [172],
       [196],
       [187],
       [172],
       [178],
       [164],
       [143],
       [191],
       [141],
       [193],
       [190],
       [175],
       [179],
       [172],
       [168],
       [164],
       [194],
       [153],
      

In [13]:
# دمج أفقي
np.hstack((col1.reshape(-1,1),col3.reshape(-1,1)))

array([[174,   4],
       [189,   2],
       [185,   4],
       [195,   3],
       [149,   3],
       [189,   3],
       [147,   5],
       [154,   5],
       [174,   3],
       [169,   4],
       [195,   2],
       [159,   4],
       [192,   3],
       [155,   2],
       [191,   2],
       [153,   5],
       [157,   5],
       [140,   5],
       [144,   5],
       [172,   5],
       [157,   5],
       [153,   5],
       [169,   4],
       [185,   5],
       [172,   2],
       [151,   3],
       [190,   3],
       [187,   1],
       [163,   5],
       [179,   5],
       [153,   5],
       [178,   1],
       [195,   1],
       [160,   5],
       [157,   5],
       [189,   4],
       [197,   3],
       [144,   4],
       [171,   5],
       [185,   2],
       [175,   4],
       [149,   5],
       [157,   2],
       [161,   5],
       [182,   4],
       [185,   2],
       [188,   4],
       [181,   4],
       [161,   3],
       [140,   5],
       [168,   5],
       [176,   1],
       [163,

In [14]:
# دمج عامودي 
np.vstack((col1.reshape(-1,1),col3.reshape(-1,1)))

array([[174],
       [189],
       [185],
       [195],
       [149],
       [189],
       [147],
       [154],
       [174],
       [169],
       [195],
       [159],
       [192],
       [155],
       [191],
       [153],
       [157],
       [140],
       [144],
       [172],
       [157],
       [153],
       [169],
       [185],
       [172],
       [151],
       [190],
       [187],
       [163],
       [179],
       [153],
       [178],
       [195],
       [160],
       [157],
       [189],
       [197],
       [144],
       [171],
       [185],
       [175],
       [149],
       [157],
       [161],
       [182],
       [185],
       [188],
       [181],
       [161],
       [140],
       [168],
       [176],
       [163],
       [172],
       [196],
       [187],
       [172],
       [178],
       [164],
       [143],
       [191],
       [141],
       [193],
       [190],
       [175],
       [179],
       [172],
       [168],
       [164],
       [194],
       [153],
      

In [15]:
# عكس ترتيب عناصر المتجه
arr[::-1]

array([[173, 131,   5],
       [150,  95,   5],
       [141, 136,   5],
       ...,
       [185, 110,   4],
       [189,  87,   2],
       [174,  96,   4]], dtype=int64)

In [16]:
# عكس ترتيب عناصر المتجهات الداخلية
arr[:,::-1]

array([[  4,  96, 174],
       [  2,  87, 189],
       [  4, 110, 185],
       ...,
       [  5, 136, 141],
       [  5,  95, 150],
       [  5, 131, 173]], dtype=int64)

In [17]:
# معلومات إحصائية عن البيانات 
heights = arr[:,0]
print('max heights = ',heights.max(),'cm')
print('min heights = ',heights.min(),'cm')
print('mean heights = ',heights.mean(),'cm')
print('standard deviation heights = ',heights.std(),'cm')

max heights =  199 cm
min heights =  140 cm
mean heights =  169.944 cm
standard deviation heights =  16.35887722308594 cm


In [18]:
# معلومات إحصائية عن البيانات 
weights = arr[:,1]
print('max weights = ',weights.max(),'kg')
print('min weights = ',weights.min(),'kg')
print('mean weights = ',weights.mean(),'kg')
print('standard deviation weights = ',weights.std(),'kg')

max weights =  160 kg
min weights =  50 kg
mean weights =  106.0 kg
standard deviation weights =  32.350208654659404 kg


In [19]:
# إيجاد العناصر الدالة على توزيع البيانات
# حيث أن 25% من البيانات أصغر من 156
np.percentile(heights,[25,50,75])

array([156. , 170.5, 184. ])

In [20]:
# حيث أن75% من البيانات أصغر من 136
np.percentile(weights,[25,50,75])

array([ 80., 106., 136.])

In [21]:
# فهرس أكبر عنصر
np.argmax(heights)

100

In [22]:
# فهرس أصغر عنصر 
np.argmin(weights)

85

In [23]:
heights[100]

199

In [24]:
weights[106]

160