In [1]:
import numpy as np

In [2]:
# إنشاء متحه صفري بعشرة مساقط
vector = np.zeros(10)
vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# إنشاء مصفوفة صفرية بعدها(10،2)
matrix= np.zeros((10,2))
matrix

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [4]:
# إنشاء متحه عناصره 1 بعشرة مساقط
vector = np.ones(10)
vector

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
# إنشاء مصفوفة عناصرها 1 بعدها(10،2)
matrix= np.ones((10,2))
matrix

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
# empty يأخذ عناصره من الذاكرة العشوائية أي ليس لقيمه معنى
# إستفدنا من ذلك بإنشاء متجه قيم مفقودة
nan1d = np.empty(10)
nan1d[:] = np.nan
nan1d

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [7]:
# إنشاء مصفوفة قيم مفقودة
nan2d = np.empty((10,2))
nan2d[:] = np.nan
nan2d

array([[nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan]])

In [8]:
#إنشاء متجه بنطاق معين   
vector = np.arange(1,10)
vector

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#إنشاء متجه بنطاق معين 
vector = np.arange(1,20,2)
vector

In [9]:
# عكس ترتيب قيم هذا المتجه
vector = np.arange(1,20,2)
vector = vector[::-1]
vector

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [10]:
# إنشاء مصفوفة بشكل معين 
matrix = np.arange(4).reshape((2,2))
matrix

array([[0, 1],
       [2, 3]])

In [ ]:
# إنشاء مصفوفة بشكل معين 
matrix = np.arange(9).reshape((3,3))
matrix

In [11]:
# معرفة موضع العناصر غير الصفرية
numbers = [1,4,5,0,8,4,5,0]
zerosindices = np.nonzero(numbers)
zerosindices

(array([0, 1, 2, 4, 5, 6], dtype=int64),)

In [12]:
# إنشاء مصفوفة واحدية
id1 = np.eye(3)
id1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# إنشاء مصفوفة واحدية
id1 = np.eye(10)
id1

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [14]:
# إنشاء متجه بعناصر عشوائية
array = np.random.random((5))
array

array([0.22303427, 0.1945504 , 0.35556919, 0.24879442, 0.58544403])

In [16]:
# إنشاء مصفوفة بعناصر عشوائية
matrix = np.random.random((5,3))
matrix

array([[0.90045886, 0.128074  , 0.27722704],
       [0.10215981, 0.31137768, 0.02402705],
       [0.79647567, 0.52107853, 0.08001731],
       [0.8146785 , 0.71956441, 0.41316524],
       [0.21342001, 0.33571699, 0.2053948 ]])

In [17]:
# معرفة أكبر و أصفر قيم في المصفوفة
matrix = np.random.random((5,5))
print(matrix)
print()
min, max = matrix.min(), matrix.max()
print('min =',min)
print('max =',max)

[[0.48545303 0.80545996 0.60415119 0.31132744 0.80895944]
 [0.13009234 0.40889065 0.79080335 0.32724134 0.28820267]
 [0.64295453 0.09105086 0.22755967 0.63873301 0.90156096]
 [0.10297099 0.89292915 0.74986991 0.67570531 0.15927295]
 [0.65208552 0.00904423 0.45443025 0.32238464 0.90271431]]

min = 0.00904423125030629
max = 0.902714311632011


In [18]:
# إيجاد متوسط قيم المتجه
vector = np.arange(1,10)
print('mean of vector= ',vector.mean())


mean of vector=  5.0


In [19]:
# معرفة شكل المتجه
array = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(array.shape)
array

(2, 3, 3)


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [20]:
# إنشاء مصفوفة بشكل معين
array1 = np.arange(1,19).reshape((2,3,3))
array1

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [21]:
#  متجه عشوائي بشكل معين بعناصر صحيحة
array1 = np.random.randint(10,size=(2,3,3))
array1

array([[[5, 3, 8],
        [5, 3, 3],
        [5, 0, 9]],

       [[5, 2, 3],
        [3, 5, 6],
        [0, 6, 0]]])

In [23]:
# إنشاء متجه بعنصر محدد 
matrix = np.full((3,3),5)
matrix

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [24]:
# تلاعب بعناصر المصفوفة
matrix = np.ones((4,4))
matrix[1:3] = 0
matrix

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [25]:
# تلاعب بعناصر المصفوفة
matrix = np.ones((4,4))
matrix[1:-1] = 0
matrix

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [26]:
# تلاعب بعناصر المصفوفة
matrix = np.ones((4,4))
matrix[:,1:-1] = 0
matrix

array([[1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.]])

In [27]:
# تلاعب بعناصر المصفوفة
matrix = np.ones((4,4))
matrix[1:-1,1:-1] = 0
matrix

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [28]:
# تلاعب بعناصر المصفوفة
matrix = np.ones((4,4))
matrix[1:-1,:] = 0
matrix[:,1:-1] = 0 
matrix

array([[1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.]])

In [29]:
# تلاعب بعناصر المصفوفة
matrix = np.ones((4,4))
matrix[:,1:-1] = 0
matrix[1:-1,] = 0 
matrix

array([[1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.]])

In [30]:
# تلاعب بعناصر المصفوفة
matrix = np.full((5,5),3)
matrix[1:-1,1:-1] = 2
matrix[2:3,2:3] = 1
matrix 

array([[3, 3, 3, 3, 3],
       [3, 2, 2, 2, 3],
       [3, 2, 1, 2, 3],
       [3, 2, 2, 2, 3],
       [3, 3, 3, 3, 3]])

In [31]:
# تلاعب بعناصر المصفوفة
matrix = np.full((5,5),3)
matrix[1:-1,1:-1] = 2
matrix[2:3,2:3] = 1
print(matrix)
print()
inner_mat = matrix[1:-1,1:-1]
inner_mat

[[3 3 3 3 3]
 [3 2 2 2 3]
 [3 2 1 2 3]
 [3 2 2 2 3]
 [3 3 3 3 3]]



array([[2, 2, 2],
       [2, 1, 2],
       [2, 2, 2]])

In [34]:
# تدوير المصفوفة
matrix = np.arange(1,3*3+1).reshape(3,3)
print(matrix)
print()
rotate_matrix_left = np.rot90(matrix)
rotate_matrix_left

[[1 2 3]
 [4 5 6]
 [7 8 9]]



array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [36]:
# تدوير المصفوفة
matrix = np.arange(1,3*3+1).reshape(3,3)
print(matrix)
print()
rotate_matrix_right = np.rot90(matrix,-1)
rotate_matrix_right

[[1 2 3]
 [4 5 6]
 [7 8 9]]



array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [41]:
# إنشاء مصفوفة قطرية من عناصر المتجه 
array = np.array([7,7,7,7])
matrix = np.diag(array)
matrix

array([[7, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 7]])

In [42]:
# إستخلاص عناصر القطر الرئيسي للمصفوفة
matrix = np.arange(4*4).reshape(4,4)
print(matrix)
print()
digarr = np.diag(matrix)
digarr 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



array([ 0,  5, 10, 15])

In [43]:
# إستخلاص عناصر ذات صفة قطرية للمصفوفة
matrix = np.arange(4*4).reshape(4,4)
print(matrix)
print()
digarr = np.diag(matrix,-1)
digarr 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



array([ 4,  9, 14])

In [45]:
# إستخلاص عناصر ذات صفة قطرية للمصفوفة
matrix = np.arange(4*4).reshape(4,4)
print(matrix)
print()
digarr = np.diag(matrix,+1)
digarr 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



array([ 1,  6, 11])

In [46]:
# إستخلاص القطر الثانوي للمصفوفة
matrix = np.arange(4*4).reshape(4,4)
print(matrix)
print()
digarr = np.diag(np.rot90(matrix))
digarr 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



array([ 3,  6,  9, 12])

In [67]:
# إنشاء مصفوفة
matrix = np.arange(25).reshape(5,5)
matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [68]:
import pandas as pd

In [69]:
# نسطيع الإشارة الى عنصر في المصفوفة بطريقتين
# liner_index ذكر العنصر بذاته
# عن طريق ثنائية تدل على موقعه
# سوف ندرس العنصر 17
pd.DataFrame(matrix)

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [70]:
# إيجاد موقع 17 في المصفوفة ذات الشكل المذكور 
liner_index = 17
non_liner_index = np.unravel_index(liner_index,(5,5))

In [73]:
liner_index , non_liner_index

(17, (3, 2))

In [74]:
liner_index = 13
non_liner_index = np.unravel_index(liner_index,(5,5))

In [75]:
liner_index ,non_liner_index

(13, (2, 3))

In [76]:
liner_index = 11
non_liner_index = np.unravel_index(liner_index,(5,5))

In [77]:
liner_index,non_liner_index 

(11, (2, 1))

In [83]:
# إيجاد العنصر ذا الموقع المذكور
non_liner_index = (3,4)
liner_index = np.ravel_multi_index(non_liner_index,(5,5))

In [84]:
non_liner_index ,liner_index

((3, 4), 19)

In [86]:
matrixA = np.arange(1,7).reshape(2,3)
matrixA

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
matrixB = np.arange(7,13).reshape(3,2)
matrixB

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [88]:
# جداء لمصفوفتين حيث عدد أعمدة الأولى يساوي عدد أسطر الثانية
product_mat = np.dot(matrixA,matrixB)
product_mat

array([[ 58,  64],
       [139, 154]])

In [89]:
# عكس إشارة متجه
array = np.arange(11)
array[:] *= -1
array

array([  0,  -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10])

In [90]:
# إنشاء متجه بعناصر عشوائية بسياق معين
array = np.random.uniform(low= -10,high= 10,size= 10)
array

array([ 3.79517308,  7.64005886,  5.8877347 , -2.789472  , -6.64111846,
       -3.56613774, -8.2521364 , -7.42764984,  6.33584845,  6.91198949])

In [91]:
# تقريب الى الأعلى
np.ceil(array)

array([ 4.,  8.,  6., -2., -6., -3., -8., -7.,  7.,  7.])

In [95]:
# تقريب الى الأدنى
np.floor(array)

array([ 3.,  7.,  5., -3., -7., -4., -9., -8.,  6.,  6.])

In [93]:
# تقريب عددي 
np.round(array)

array([ 4.,  8.,  6., -3., -7., -4., -8., -7.,  6.,  7.])

In [96]:
#  جمع عناصر متجه الى مصفوفة على المحور 0  
matrix = np.ones((5,5))
matrix +=np.arange(5)
matrix

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

In [99]:
# جمع عناصر متجه الى مصفوفة على المحور 1 
matrix = np.ones((5,5))
matrix +=np.arange(5).reshape((5,1))
matrix

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [100]:
matrix = np.arange(10).reshape(2,5)
matrix

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [101]:
# منقول مصفوفة
matrix.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [102]:
matrix = np.arange(10,20).reshape(2,5)
matrix

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [103]:
# منقول مصفوفة
np.transpose(matrix)

array([[10, 15],
       [11, 16],
       [12, 17],
       [13, 18],
       [14, 19]])

In [104]:
# تمديد بطريقة محددة
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.append(arr1,arr2)
arr3

array([1, 2, 3, 4, 5, 6])

In [124]:
# تمديد بطريقة محددة
# وجب ان يكون البعد الذي تم التمديد عليه متساوي  
matrix = np.array([[1,2],[3,4]])
array = np.array([5,6]).reshape(2,1)

In [125]:
print(array.shape,'\n')
matrix.shape

(2, 1) 



(2, 2)

In [126]:
print(array,'\n')
matrix

[[5]
 [6]] 



array([[1, 2],
       [3, 4]])

In [127]:
arr = np.append(matrix,array,axis=1)
arr

array([[1, 2, 5],
       [3, 4, 6]])

In [128]:
# إنتبه الى المحور الذي نجري عليه التمديد
matrix = np.array([[1,2],[3,4]])
array = np.array([5,6]).reshape(1,2)

In [130]:
arr = np.append(matrix,array,axis=0)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [131]:
# هنا جميع الأبعاد متساوية فلا يوجد مشكلة 
matrix = np.array([[1,2],[3,4]])
array = np.array([[5,6],[7,8]])

In [132]:
arr = np.append(matrix,array,axis=0)
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [133]:
arr = np.append(matrix,array,axis=1)
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])